<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "streamchartz_api"
 *
 * Auto generated by Extension Builder 2016-01-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Streamchartz',
	'description' => 'Streamchartz Plugin',
	'category' => 'fe',
	'author' => 'Marko Ellermaa',
	'author_email' => 'm.ellermaa@bluforce.at',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.5',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-9.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);